name: pharmacy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_storage: ^12.2.0
  cloud_firestore: ^5.3.0
  flutter_riverpod: ^2.5.1
  fluttertoast: ^8.2.8
  fpdart: ^1.1.0
  freezed: ^2.5.2
  json_annotation: ^4.9.0
  intl: ^0.19.0
  dotted_line: ^3.2.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  http_auth: ^1.0.4
  flutter_paypal_checkout: ^1.0.1
  flutter_paypal: ^0.2.0
  flutter_dash: ^1.0.0
  image_picker: ^1.1.2
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  flutter_stripe: ^11.0.0
  routemaster: ^1.0.1
  uuid: ^4.5.0
  get: ^4.6.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
